name: Release

on:
  push:
    tags: ["v[0-9]+.[0-9]+.[0-9]+*"]

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  CARGO_TERM_COLOR: always

jobs:
  macos:
    runs-on: macos-latest
    permissions:
      contents: write
      packages: write

    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: brew install scdoc
      - name: Install ARM target··
        run: rustup update && rustup target add aarch64-apple-darwin && rustup target add x86_64-apple-darwin
      - name: Test
        run: cargo test --release --target=x86_64-apple-darwin
      - name: Build ARM
        run: cargo build --release --target=aarch64-apple-darwin
      - name: Make DMG
        run: |
          make dmg-universal
          mv ./target/release/osx/Alacritty.dmg ./Alacritty-${{ github.ref_name }}.dmg
      - name: Upload Release Asset
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          files: |
            Alacritty-${{ github.ref_name }}.dmg 
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  # windows:
  #   runs-on: windows-latest

  #   defaults:
  #     run:
  #       shell: bash

  #   steps:
  #     - uses: actions/checkout@v4
  #     - name: Test
  #       run: cargo test --release
  #     - name: Build
  #       run: cargo build --release
  #     - name: Upload portable executable
  #       run: |
  #         cp ./target/release/alacritty.exe ./Alacritty-${{ github.ref_name }}-portable.exe
  #     - name: Install WiX
  #       run: dotnet tool install --global wix --version 4.0.5
  #     - name: Create msi installer
  #       run: |
  #         wix extension add WixToolset.UI.wixext/4.0.5 WixToolset.Util.wixext/4.0.5
  #         wix build -arch "x64" -ext WixToolset.UI.wixext -ext WixToolset.Util.wixext \
  #         -out "./Alacritty-${{ github.ref_name }}-installer.msi" "alacritty/windows/wix/alacritty.wxs"
  #     - name: Upload msi installer
  #       uses: softprops/action-gh-release@v2
  #       with:
  #         tag_name: ${{ github.ref_name }}
  #         files: |
  #           Alacritty-${{ github.ref_name }}-installer.msi
  #           Alacritty-${{ github.ref_name }}-portable.exe
  #       env:
  #         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  # linux:
  #   runs-on: ubuntu-latest

  #   steps:
  #     - uses: actions/checkout@v4
  #     - name: Install dependencies
  #       run: |
  #         sudo apt-get install cmake pkg-config libfreetype6-dev libfontconfig1-dev \
  #           libxcb-xfixes0-dev libxkbcommon-dev python3 scdoc
  #     - name: Test
  #       run: cargo test --release
  #     - name: Generate manpages
  #       run: |
  #         scdoc < extra/man/alacritty.1.scd | gzip -c > "./alacritty.1.gz"
  #         scdoc < extra/man/alacritty-msg.1.scd | gzip -c > "./alacritty-msg.1.gz"
  #         scdoc < extra/man/alacritty.5.scd | gzip -c > "./alacritty.5.gz"
  #         scdoc < extra/man/alacritty-bindings.5.scd | gzip -c > "./alacritty-bindings.5.gz"
  #         mv ./extra/logo/alacritty-term.svg ./Alacritty.svg
  #     - name: Upload Assets
  #       uses: softprops/action-gh-release@v2
  #       with:
  #         tag_name: ${{ github.ref_name }}
  #         files: |
  #           Alacritty.svg
  #           alacritty.1.gz
  #           alacritty-msg.1.gz
  #           alacritty.5.gz
  #           alacritty-bindings.5.gz
  #           extra/completions/alacritty.bash
  #           extra/completions/alacritty.fish
  #           extra/completions/_alacritty
  #           extra/linux/Alacritty.desktop
  #           extra/alacritty.info
  #       env:
  #         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

